# Autogenerated by Ansible, do not edit manually.

#
# .zshenv: Zsh environment file, loaded always.
#

# Functions

addToPathFront() {
    if [[ "$PATH" != *"$1"* ]]; then
        export PATH=$1:$PATH
    fi
}

# XDG Paths as per the specification:
# https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
export XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}
export XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-$HOME/.xdg}

# Custom XDG Paths
export XDG_PERSONAL_DIR=${XDG_PERSONAL_DIR:-$HOME/Personal}
export XDG_WORK_DIR=${XDG_WORK_DIR:-$HOME/Work}
export XDG_PULSTAR_DIR=${XDG_PULSTAR_DIR:-$HOME/pulstar}

# Add paths
addToPathFront "$HOME/.local/bin"

# Other
export CDPATH=".:$HOME:$XDG_PERSONAL_DIR:$XDG_WORK_DIR:$XDG_DOCUMENTS_DIR:$XDG_DOWNLOADS_DIR:$XDG_IDEAS_DIR"
export EDITOR="nvim"
export TERMINAL="ghostty"
